-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 22:38:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `UserID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `AccountVerified` TINYINT NULL DEFAULT FALSE,
  `AccountBlocked` TINYINT NULL DEFAULT FALSE,
  `Invitations` INT NULL DEFAULT 0,
  `SubscriptionID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX (`Email` ASC) VISIBLE,
  INDEX (`SubscriptionID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`SubscriptionID`)
    REFERENCES `mydb`.`Subscription` (`SubscriptionID`));


-- -----------------------------------------------------
-- Table `mydb`.`ContentWarnings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ContentWarnings` (
  `ContentWarningID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ContentWarningID`));


-- -----------------------------------------------------
-- Table `mydb`.`Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Episode` (
  `EpisodeId` INT NOT NULL,
  `SeriesId` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Subtitles` VARCHAR(45) NULL,
  `PrevEp` VARCHAR(45) NULL,
  `NextEp` VARCHAR(45) NULL,
  PRIMARY KEY (`EpisodeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Film` (
  `FilmID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL,
  `Subtitles` TINYINT NULL DEFAULT FALSE,
  `MinimumAge` INT NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `TimesWatched` INT NULL DEFAULT 0,
  PRIMARY KEY (`FilmID`));


-- -----------------------------------------------------
-- Table `mydb`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres` (
  `GenresID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Genre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`GenresID`));


-- -----------------------------------------------------
-- Table `mydb`.`Genres_Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres_Film` (
  `FilmID` INT NOT NULL,
  `GenresID` INT NULL DEFAULT NULL,
  `Genres` VARCHAR(45) NULL,
  PRIMARY KEY (`GenresID`, `FilmID`),
  INDEX (`GenresID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`FilmID`)
    REFERENCES `mydb`.`Film` (`FilmID`),
  CONSTRAINT ``
    FOREIGN KEY (`GenresID`)
    REFERENCES `mydb`.`Genres` (`GenresID`));


-- -----------------------------------------------------
-- Table `mydb`.`Genres_Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres_Profile` (
  `ProfileID` INT NULL DEFAULT NULL,
  `GenresID` INT NULL DEFAULT NULL,
  `Genres` VARCHAR(45) NULL,
  PRIMARY KEY (`ProfileID`, `GenresID`),
  INDEX (`GenresID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`ProfileID`)
    REFERENCES `mydb`.`Profile` (`ProfileID`),
  CONSTRAINT ``
    FOREIGN KEY (`GenresID`)
    REFERENCES `mydb`.`Genres` (`GenresID`));


-- -----------------------------------------------------
-- Table `mydb`.`Genres_Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres_Series` (
  `SeriesID` INT NULL DEFAULT NULL,
  `GenresID` INT NULL DEFAULT NULL,
  `Genres` VARCHAR(45) NULL,
  PRIMARY KEY (`SeriesID`, `GenresID`),
  INDEX (`GenresID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`SeriesID`)
    REFERENCES `mydb`.`Series` (`SeriesID`),
  CONSTRAINT ``
    FOREIGN KEY (`GenresID`)
    REFERENCES `mydb`.`Genres` (`GenresID`));


-- -----------------------------------------------------
-- Table `mydb`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profile` (
  `ProfileID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `UserID` INT NULL DEFAULT NULL,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Photo` VARCHAR(255) NULL DEFAULT NULL,
  `Language` VARCHAR(50) NULL DEFAULT NULL,
  `Age` INT NULL DEFAULT NULL,
  `InterestedInMedia` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ProfileID`),
  INDEX (`UserID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Account` (`UserID`));


-- -----------------------------------------------------
-- Table `mydb`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Series` (
  `SeriesID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL,
  `Subtitles` TINYINT NULL DEFAULT FALSE,
  `MinimumAge` INT NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `TimesWatched` INT NULL DEFAULT 0,
  PRIMARY KEY (`SeriesID`));


-- -----------------------------------------------------
-- Table `mydb`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subscription` (
  `SubscriptionID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `SubscriptionType` VARCHAR(100) NOT NULL,
  `Discount` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`SubscriptionID`));


-- -----------------------------------------------------
-- Table `mydb`.`WatchingFilm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WatchingFilm` (
  `ProfileID` INT NULL DEFAULT NULL,
  `FilmID` INT NULL DEFAULT NULL,
  `PausedTime` TIME NULL DEFAULT NULL,
  `WatchCount` INT NULL DEFAULT 0,
  PRIMARY KEY (`ProfileID`, `FilmID`),
  INDEX (`FilmID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`ProfileID`)
    REFERENCES `mydb`.`Profile` (`ProfileID`),
  CONSTRAINT ``
    FOREIGN KEY (`FilmID`)
    REFERENCES `mydb`.`Film` (`FilmID`));


-- -----------------------------------------------------
-- Table `mydb`.`WatchingSeries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WatchingSeries` (
  `ProfileID` INT NULL DEFAULT NULL,
  `SeriesID` INT NULL DEFAULT NULL,
  `PausedTime` TIME NULL DEFAULT NULL,
  `WatchCount` INT NULL DEFAULT 0,
  `CurrentEpisode` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ProfileID`, `SeriesID`),
  INDEX (`SeriesID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`ProfileID`)
    REFERENCES `mydb`.`Profile` (`ProfileID`),
  CONSTRAINT ``
    FOREIGN KEY (`SeriesID`)
    REFERENCES `mydb`.`Series` (`SeriesID`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
